Replace `DateTime` with `DateTimeImmutable`
avtocod/b2b-api-php pull request #23
Opened 2020-10-15 04:30 UTC by gomzyakov

## Description

### Changed

- Replace `DateTime` with `DateTimeImmutable`

Fixes #21 

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I wrote unit tests for my code _(if tests is required for my changes)_
- [ ] I have made changes in `CHANGELOG.md` file

2020-10-15 04:38 UTC, gomzyakov commented on tests/Unit/Responses/Entities/EntitiesFactory.php
> +                    : DateTimeImmutable::createFromMutable($faker->dateTimeThisMonth),
I can get refactoring of this code & similar code below.

But, this is beyond the scope of the task, right?

2020-10-15 11:46 UTC, eldario requested changes

2020-10-15 11:46 UTC, eldario commented on tests/Unit/ClientTest.php
> +                    'stamp' => $stamp = DateTimeFactory::toIso8601Zulu(new DateTimeImmutable()),
del `()`

2020-10-15 11:46 UTC, eldario commented on tests/Unit/ClientTest.php
> +                'date'    => DateTimeFactory::toIso8601ZuluWithoutMs($date = new DateTimeImmutable()),
del `()`

2020-10-15 13:23 UTC, gomzyakov commented on tests/Unit/ClientTest.php
> +                'date'    => DateTimeFactory::toIso8601ZuluWithoutMs($date = new DateTimeImmutable()),
Fixed 6b3bd06c0b6414c6ee11bc614c2003c1b22a17ee

2020-10-15 13:23 UTC, gomzyakov commented on tests/Unit/ClientTest.php
> +                    'stamp' => $stamp = DateTimeFactory::toIso8601Zulu(new DateTimeImmutable()),
Fixed 6b3bd06c0b6414c6ee11bc614c2003c1b22a17ee

2020-10-19 11:10 UTC, tarampampam commented
Blocked until #22 is not merged

2020-10-22 10:46 UTC, closed without merging