Add support composer 2 and php 8.0
avtocod/b2b-api-php pull request #33
Opened 2021-04-16 12:33 UTC by 4irik

## Description

Add support composer 2 and php 8.0

Fixes #30

## Checklist

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I wrote unit tests for my code _(if tests is required for my changes)_
- [x] I have made changes in `CHANGELOG.md` file

2021-04-28 01:07 UTC, blackbass1988 commented
поставь все галочки)

2021-05-13 09:24 UTC, IgorKorytin requested changes
1. Remove `--no-suggest` key from composer scripts where key `-n` used (makefile, github actions)
2. Add `-e 'XDEBUG_MODE=coverage'` to `make test-cover` script, and add this env to github actions
3.  Do you check `make test-cover` scpipt on PHP 8 and `latest` config? Think it will not work or u'll get a deprecated warning

2021-05-13 09:24 UTC, IgorKorytin commented on Dockerfile
>      COMPOSER_ALLOW_SUPERUSER="1" \
This env is unused in composer 2

2021-05-13 09:24 UTC, IgorKorytin commented on Dockerfile
> -    && composer global require 'hirak/prestissimo' --no-interaction --no-suggest --prefer-dist \
Remove it from github actions workflow too please

2021-05-13 09:24 UTC, IgorKorytin commented on composer.json
> +        "php": "^7.2 || ^8.0",
change php version in `composer.json` and add php 8 to github actions

2021-05-13 09:24 UTC, IgorKorytin commented on Dockerfile
>      && pecl install xdebug-2.9.6 1>/dev/null \
maybe update it to v 3?

2021-06-09 05:16 UTC, eldario commented
@4irik 
Please, make some changes by threads

2022-01-10 07:03 UTC, eldario commented
No activity

2022-01-10 07:03 UTC, closed without merging